#!/usr/local/bin/perl -w
use strict;

#----------------------------------------------------
#RECUPERAR DATOS
#create the script file codetr.scp with the following:
#/home/.../testData/testT0001.wav /home/../testData/testT0001.mfc
#/home/.../testData/testT0002.wav /home/../testData/testT0002.mfc
#/home/.../testData/testT0003.wav /home/../testData/testT0003.mfc
#
system('perl makeCodetst codetst.scp /home/jorjasso/SpeechRecognitionSystem/version0.3/trainingData');


#PARA LOS DATOS DE TEST Y ENTRENAMIENTO
system('HCopy -T 1 -C configTest0 -S codetst.scp');
print "Entrenamiento Finalizado\n";
#CREAR ARCHIVO test.scp
system('perl makeTestScp test.scp /home/jorjasso/SpeechRecognitionSystem/version0.3/trainingData');

system('HVite -H hmm15/macros -H hmm15/hmmdefs -C configHVite -S test.scp -l ‘*’ -i recout.mlf -w wdnet -p 0 -s 5 dict tiedlist');
 

#VERIFICAR recout.mlf 
system('perl recoutModified recout.mlf recout1.mlf');

system('perl testrefModified testref.mlf testref1.mlf');

#ESCRIBIR RESULTADOS
system('HResults -a ENVIADAS -b PALABRAS -t  -f  -I testref1.mlf tiedlist recout1.mlf>>results1');


