#!/usr/local/bin/perl -w
use strict;

my ($phones0,$phones1,$line,$flag);

if (@ARGV != 2) {
  print "usage: $0 mlf promptlist\n\n"; 
  exit (0);
}

# read in command line arguments
($phones0,$phones1) = @ARGV;



# open phone0 file
open (LAB, "$phones0") || die ("Unable to open prompt file $phones0");
open (PHONE, ">$phones1") || die ("Unable to open prompt file $phones1");

while ($line=<LAB>) {
   
  if ($line =~ /\"/)
  { 
    $line =~s/\"\’\*\’/\"*/; 
    print PHONE ("$line");
  }
  else  
  {
    print PHONE $line;
  }
}

close (LAB);
close (PHONE);


